// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef Diplom_h
#define Diplom_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Group.H>
#include "function.h"
extern Fl_Group *Group_Main;
#include <FL/Fl_Input.H>
extern Fl_Input *Input_Sign_In_Email;
extern Fl_Input *Input_Password;
#include <FL/Fl_Button.H>
extern Fl_Button *Button_Login;
extern Fl_Button *Button_Main_SignUp;
extern Fl_Button *Button_Main_Reset;
#include <FL/Fl_Output.H>
extern Fl_Output *Output_Error_Logs_Main;
extern Fl_Group *Group_Message;
extern Fl_Input *Input_To;
extern Fl_Input *Input_Subject;
extern Fl_Input *Input_Text;
extern Fl_Button *Button_Send_Message;
extern Fl_Button *Button_Back_In_Message_Group;
extern Fl_Group *Group_Menu;
extern Fl_Button *Button_Compose;
extern Fl_Button *Button_Sent;
extern Fl_Button *Button_Spam;
extern Fl_Button *Button_Settings;
extern Fl_Button *Button_Menu_SignUp;
#include <FL/Fl_Check_Browser.H>
extern Fl_Check_Browser *Browser_Received;
extern Fl_Output *Output_Name;
extern Fl_Output *Output_Lastname;
extern Fl_Button *Button_Watch;
extern Fl_Button *Button_Send_To_Spam;
extern Fl_Group *Group_Settings;
extern Fl_Group *Group_AES;
#include <FL/Fl_Round_Button.H>
extern Fl_Round_Button *Button_128_bit;
extern Fl_Round_Button *Button_192_bit;
extern Fl_Round_Button *Button_256_bit;
extern Fl_Group *Group_RSA;
extern Fl_Round_Button *Button_RSA_2048;
extern Fl_Round_Button *Button_RSA_4096;
extern Fl_Round_Button *Button_Manual;
extern Fl_Round_Button *Button_Custom;
extern Fl_Button *Button_Settings_Next;
extern Fl_Button *Button_Settings_Back;
extern Fl_Group *Group_HASH;
extern Fl_Round_Button *Button_SHA_512;
extern Fl_Round_Button *Button_MD5;
extern Fl_Button *Button_User_Settings_Other;
extern Fl_Group *Group_Secure;
extern Fl_Group *Group_Remember_this_Number;
extern Fl_Button *Button_Next_Secure_Number;
#include <FL/Fl_Value_Output.H>
extern Fl_Value_Output *Output_Secure_Number;
extern Fl_Group *Group_Pleas_Read_your_Number;
extern Fl_Button *Button_Next_Input_Secure_Number;
#include <FL/Fl_Value_Input.H>
extern Fl_Value_Input *Input_Secure_Number;
extern Fl_Group *Group_Welcome;
extern Fl_Output *Output_Welcome;
extern Fl_Button *Button_Welcom_Sleep;
extern Fl_Group *Group_Registration;
extern Fl_Group *Group_Registration_Page1;
extern Fl_Input *Input_Sign_Up_Email;
extern Fl_Button *Button_Sign_Up;
extern Fl_Button *Button_Sign_Up_Back;
extern Fl_Output *Output_Email_Valid_Message;
extern Fl_Group *Group_Registration_Page2;
extern Fl_Input *Input_Confirm;
extern Fl_Button *Button_Confirm;
extern Fl_Button *Button_Confirm_Back;
extern Fl_Output *Output_Please_Check_Your_Email;
extern Fl_Group *Group_Registration_Page3;
extern Fl_Button *Button_Confirm_Skip;
extern Fl_Output *Output_Scssesful;
extern Fl_Group *Group_User_Settings;
extern Fl_Input *Input_User_Settings_Name;
extern Fl_Input *Input_User_Settings_LastName;
extern Fl_Input *Input_User_Settings_Password;
extern Fl_Input *Input_User_Settings_NewPassword;
extern Fl_Input *Input_User_Settings_NewPassword_Repl;
extern Fl_Button *Button_User_Settings_Save;
extern Fl_Button *Button_User_Settings_Cancel;
extern Fl_Group *Group_Yes_OR_No;
extern Fl_Button *Button_User_Settings_No;
extern Fl_Button *Button_User_Settings_Yes;
extern Fl_Group *Group_Spam;
extern Fl_Button *Button_Spam_Delete;
extern Fl_Button *Button_Spam_Delete_All;
extern Fl_Check_Browser *Browser_Spam_List;
extern Fl_Button *Button_Spam_Back;
extern Fl_Button *Button_Spam_Restore;
extern Fl_Group *Group_Sent;
extern Fl_Button *Button_Sent_Compose;
extern Fl_Check_Browser *Browser_Sent_List;
extern Fl_Output *Output_Sent_Message;
extern Fl_Button *Button_Sent_Back;
extern Fl_Button *Button_Sent_Watch;
extern Fl_Group *Group_Reset;
extern Fl_Input *Input_Reset_Email;
extern Fl_Button *Button_Reset;
extern Fl_Button *Button_Reset_Back;
extern Fl_Output *Output_Email_Reset_Valid_Message;
extern Fl_Group *Group_Reset_Step2;
extern Fl_Button *Button_Reset_End;
extern Fl_Output *Output_Reset_Message;
extern Fl_Group *Group_Watch;
extern Fl_Button *Button_Watch_Compose;
extern Fl_Check_Browser *Browser_Watch_List;
extern Fl_Output *Output_Watch_Message;
extern Fl_Button *Button_Watch_Back;
extern Fl_Output *Output_Watch_Email;
#endif
